/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ITEP;

/**
 *
 * @author Ankit-Meena
 */
public class Admin1 extends javax.swing.JFrame {

    /**
     * Creates new form Staff
     */
    public Admin1() {
        initComponents();
        setExtendedState(Admin1.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Delete = new javax.swing.JButton();
        Interview = new javax.swing.JButton();
        Exam_RE = new javax.swing.JButton();
        Final_Re = new javax.swing.JButton();
        Crete_class = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Delete.setBackground(new java.awt.Color(153, 153, 153));
        Delete.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user-delete.png"))); // NOI18N
        Delete.setText("Delete Stu..");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 234, -1));

        Interview.setBackground(new java.awt.Color(153, 153, 153));
        Interview.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        Interview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        Interview.setText("InterView Upt.");
        Interview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterviewActionPerformed(evt);
            }
        });
        jPanel1.add(Interview, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 234, -1));

        Exam_RE.setBackground(new java.awt.Color(153, 153, 153));
        Exam_RE.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        Exam_RE.setForeground(new java.awt.Color(102, 102, 102));
        Exam_RE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit.png"))); // NOI18N
        Exam_RE.setText("Result Uptade");
        Exam_RE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exam_REActionPerformed(evt);
            }
        });
        jPanel1.add(Exam_RE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 234, 83));

        Final_Re.setBackground(new java.awt.Color(153, 153, 153));
        Final_Re.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        Final_Re.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Result.png"))); // NOI18N
        Final_Re.setText("Final Result");
        Final_Re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Final_ReActionPerformed(evt);
            }
        });
        jPanel1.add(Final_Re, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 230, 234, -1));

        Crete_class.setBackground(new java.awt.Color(153, 153, 153));
        Crete_class.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        Crete_class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Class.png"))); // NOI18N
        Crete_class.setText("Create Class");
        Crete_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crete_classActionPerformed(evt);
            }
        });
        jPanel1.add(Crete_class, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 234, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Website-Design-Background1234.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1390, 780));

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(255, 102, 102));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Main_Menu.png"))); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("LogOut");
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Final_ReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Final_ReActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Final_ReActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        new Delete_Student().setVisible(true);
    }//GEN-LAST:event_DeleteActionPerformed

    private void Exam_REActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exam_REActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Exam_REActionPerformed

    private void InterviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InterviewActionPerformed

    private void Crete_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crete_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Crete_classActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crete_class;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Exam_RE;
    private javax.swing.JButton Final_Re;
    private javax.swing.JButton Interview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
