/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ITEP;

import java.awt.Color;

/**
 *
 * @author Ankit-Meena
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        setExtendedState(Student.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        final1 = new javax.swing.JButton();
        ragi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        result = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        final1.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        final1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/result1.png"))); // NOI18N
        final1.setText("BALANCE");
        final1.setPreferredSize(new java.awt.Dimension(152, 59));
        final1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                final1ActionPerformed(evt);
            }
        });
        getContentPane().add(final1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 175, 76));

        ragi.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        ragi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/3D-Icon.png"))); // NOI18N
        ragi.setText("CREATE ACCOUNT");
        ragi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ragiActionPerformed(evt);
            }
        });
        getContentPane().add(ragi, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 200, 76));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel1.setText("OPEN BANK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 0, -1, -1));

        result.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Document-search-icon.png"))); // NOI18N
        result.setText("Check Result");
        result.setPreferredSize(new java.awt.Dimension(152, 59));
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 179, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/InfoBeans.png"))); // NOI18N
        jLabel2.setText("MEENA BANK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 74));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Student@Image.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -240, 2270, 1040));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
        new Check_Result().setVisible(true);
        
    }//GEN-LAST:event_resultActionPerformed

    private void ragiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ragiActionPerformed
        // TODO add your handling code here:
        new Registration().setVisible(true);
    }//GEN-LAST:event_ragiActionPerformed

    private void final1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_final1ActionPerformed
        // TODO add your handling code here:
        new Chech_Schedule().setVisible(true);
    }//GEN-LAST:event_final1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton final1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton ragi;
    private javax.swing.JButton result;
    // End of variables declaration//GEN-END:variables
}
