package ITEP;
import java.awt.*;
import javax.swing.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.regex.*;
/**
 *
 * @author Ankit-Meena
 */
public class Apply extends javax.swing.JFrame {

    /**
     * Creates new form Apply
     */
    public Apply() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        nA = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        eA = new javax.swing.JTextField();
        qA = new javax.swing.JTextField();
        iA = new javax.swing.JTextField();
        cA = new javax.swing.JTextField();
        aA = new javax.swing.JTextField();
        submitA = new javax.swing.JButton();
        nameA = new javax.swing.JLabel();
        emailA = new javax.swing.JLabel();
        qualificationA = new javax.swing.JLabel();
        incomeA = new javax.swing.JLabel();
        contactA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apply");
        setMaximumSize(new java.awt.Dimension(775, 425));
        setMinimumSize(new java.awt.Dimension(775, 425));
        setPreferredSize(new java.awt.Dimension(775, 425));
        setResizable(false);

        l1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l1.setText("Name            :");

        l2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l2.setText("Email             :");

        l3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l3.setText("Qualification  :");

        l4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l4.setText("Income           :");

        nA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nAActionPerformed(evt);
            }
        });
        nA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nAKeyReleased(evt);
            }
        });

        l5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l5.setText("Contact         :");

        l6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l6.setText("Address         :");

        eA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eAActionPerformed(evt);
            }
        });
        eA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eAKeyReleased(evt);
            }
        });

        qA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qAActionPerformed(evt);
            }
        });
        qA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qAKeyReleased(evt);
            }
        });

        iA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAActionPerformed(evt);
            }
        });
        iA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iAKeyReleased(evt);
            }
        });

        cA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAActionPerformed(evt);
            }
        });
        cA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cAKeyReleased(evt);
            }
        });

        aA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAActionPerformed(evt);
            }
        });
        aA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aAKeyReleased(evt);
            }
        });

        submitA.setBackground(new java.awt.Color(204, 204, 255));
        submitA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitA.setText("Submit");

        nameA.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        nameA.setForeground(new java.awt.Color(255, 0, 0));
        nameA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameAKeyReleased(evt);
            }
        });

        emailA.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        emailA.setForeground(new java.awt.Color(255, 0, 0));

        qualificationA.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        qualificationA.setForeground(new java.awt.Color(255, 0, 0));

        incomeA.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        incomeA.setForeground(new java.awt.Color(255, 0, 0));

        contactA.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        contactA.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Apply (1)12.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l1)
                                    .addComponent(l2))
                                .addComponent(l3))
                            .addComponent(l4))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eA, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qA, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(qualificationA, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iA, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cA, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailA, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nA, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameA, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aA, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(incomeA, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(submitA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(nameA, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l2)
                            .addComponent(eA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(emailA, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(qualificationA, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(iA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(l4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, 0)
                        .addComponent(incomeA, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactA, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(submitA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nAActionPerformed

    private void eAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eAActionPerformed

    private void qAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qAActionPerformed

    private void iAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iAActionPerformed

    private void cAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cAActionPerformed

    private void aAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aAActionPerformed

    private void nameAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameAKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nameAKeyReleased

    private void nAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nAKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z]{0,15}[ ][a-zA-Z]{0,15}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(nA.getText());
        if(!match.matches()){
            nameA.setText("Name must be alphabet");
        }else{
            nameA.setText(null);
        }
    }//GEN-LAST:event_nAKeyReleased

    private void eAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eAKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-z0-9]{0,20}[@][a-z]{0,10}[.][a-z]{0,4}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(eA.getText());
        if(!match.matches()){
            emailA.setText("Email isn't in format");
        }else{
            emailA.setText(null);
        }
    }//GEN-LAST:event_eAKeyReleased

    private void qAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qAKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-z0-9]{0,6}}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(qA.getText());
        if(!match.matches()){
            qualificationA.setText("Qualification isn't in format");
        }else{
            qualificationA.setText(null);
        }
    }//GEN-LAST:event_qAKeyReleased

    private void iAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iAKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,10}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(iA.getText());
        if(!match.matches()){
            incomeA.setText("Income to high");
        }else{
            incomeA.setText(null);
        }
    }//GEN-LAST:event_iAKeyReleased

    private void cAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cAKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{10}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(cA.getText());
        if(!match.matches()){
            contactA.setText("Contact must be 10 digits");
        }else{
            contactA.setText(null);
        }
    }//GEN-LAST:event_cAKeyReleased

    private void aAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aAKeyReleased
        // TODO add your handling code here:
       String PATTERN="^[a-zA-z0-9/,-]{0,100}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(eA.getText());
        if(!match.matches()){
            emailA.setText("Address mustn't contain special characters");
        }else{
            emailA.setText(null);
        }
    }//GEN-LAST:event_aAKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aA;
    private javax.swing.JTextField cA;
    private javax.swing.JLabel contactA;
    private javax.swing.JTextField eA;
    private javax.swing.JLabel emailA;
    private javax.swing.JTextField iA;
    private javax.swing.JLabel incomeA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JTextField nA;
    private javax.swing.JLabel nameA;
    private javax.swing.JTextField qA;
    private javax.swing.JLabel qualificationA;
    private javax.swing.JButton submitA;
    // End of variables declaration//GEN-END:variables
}
